function _defineProperty(a,b,c){return b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c,a}console.log("test");class Good{renderGood(a,b,c,d){return`     
            <div class='cotalog__product'>
                <a href='index.php?page=good/${a}' data-id='${a}' class='cotalog__nameProduct'>
                    <img src='${c}' alt='${b}' class='cotalog__img' width='100' height='190'>
                </a>
                <a href='index.php?page=good/${a}' data-id='${a}' class='cotalog__nameProduct'> ${b} </a>
                <span class='cotalog__priceProduct'>$ ${d} </span>
                <button data-id='${a}'   class='cotalog__addCart'>Добавить в корзину</button>

            </div>
        
        `}}class Shop extends Good{constructor(...a){super(...a),_defineProperty(this,"cotalog",[]),_defineProperty(this,"id_user",""),_defineProperty(this,"button_off",!1)}getCotalog(a,b,c){return document.querySelector(".contCotalog__preloader").classList.toggle("active"),fetch(a,{method:b,body:c}).then(a=>a.json()).then(a=>{this.cotalog=a.cotalog,this.id_user=a.id_user,this.button_off=a.button_off}).then(()=>{this.render(this.cotalog,this.button_off),document.querySelector(".contCotalog__preloader").classList.toggle("active"),this.__getLastEl().classList.add("active")})}render(a,b){let c=document.querySelector(".contCotalog");document.querySelector(".load").style.display=b?"none":"flex",a?a.forEach(a=>{c&&(c.innerHTML+=this.renderGood(a.id,a.name,a.linkImg,a.price,a.description))}):c.innerHTML=`<h3> По вашему запросу совпадений не найдено! </h3>`}__getLastEl(){let a=document.querySelectorAll(".cotalog");return console.log(a[a.length-1]),a[a.length-1]}}let SH=new Shop,st=1,fn=8,request=new FormData;// обработчик кнопок добавить в корзину 
request.append("startN",`${st}`),request.append("finishN",`${fn}`),SH.getCotalog("./controller/serv.php","post",request),document.querySelector(".load").addEventListener("click",()=>{st+=8,fn+=8;let a=new FormData;a.append("startN",`${st}`),a.append("finishN",`${fn}`),SH.getCotalog("./controller/serv.php","post",a)}),document.querySelector(".cotalog").addEventListener("click",function(a){if("cotalog__addCart"==a.target.className){let b=new FormData;b.append("id_product",a.target.dataset.id),b.append("id_user",SH.id_user),b.append("oper","add"),fetch("./controller/serv.php",{method:"post",body:b}).then(a=>a.json()).then(a=>{"add"==a.res&&(document.querySelector(".countCart").innerHTML=a.allQuant)})}// модальное окно с информацией о заказе
if("watchOrder"==a.target.className&&(document.querySelector(".modelWindow").classList.toggle("modelWindow-active"),document.querySelector(".modelWindow__window").classList.toggle("modelWindow__window-active"),document.querySelector(`div[data-idwin="${a.target.dataset.id}"]`).classList.toggle("modelWindow__show-active")),"modelWindow__close"==a.target.className){document.querySelector(".modelWindow").classList.toggle("modelWindow-active"),document.querySelector(".modelWindow__window").classList.toggle("modelWindow__window-active");let a=[...document.querySelectorAll(".modelWindow__show")];a.forEach(a=>{a.classList.remove("modelWindow__show-active")})}});